SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT * FROM USER;

START TRANSACTION;
UPDATE USER SET NAME = "updated" WHERE ID = 1;
INSERT INTO USER (NAME) VALUES ("new");
SELECT * FROM USER;