CREATE TABLE USER (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20)
    );

	INSERT INTO USER (NAME) VALUES ("kim");
    INSERT INTO USER (NAME) VALUES ("lee");
    INSERT INTO USER (NAME) VALUES ("park");
    
    SELECT * FROM USER;